#!/usr/bin/env python3
# BA1A
# Compute the Number of Times a Pattern Appears in a Text

def pattern_count(text, pattern):
    """Compute the Number of Times a Pattern Appears in a Text."""
    count = 0
    for i in range(len(text) - len(pattern) + 1):
        if text[i:i+len(pattern)] == pattern:
            count += 1
    return count


def main():
    """Compute the Number of Times a Pattern Appears in a Text."""
    # text = 'GCGCG'
    # pattern = 'GCG'

    text = 'CAGCTTTGCACAAGCTTTGTGCCGAAAGAACATACGCGAGAGCTTTGCTGGTCGAGCTTTGTTCAGCTTTGAGCTTTGATATTTCTTAGCTTTGAAGCTTTGAGCTTTGACCAGCTTTGTAGCTTTGCAGCTTTGAGGAGCTTTGAAGCTTTGGCGTAAGCTTTGGAGCTTTGAGTAGCTTTGAGCTTTGTGAGCTTTGAGCTTTGACGAAGCTTTGACCCAGCTTTGAGAGCTTTGGCAAGCTTTGTTGCTAGCTTTGAGCTTTGAGCTTTGATTCCGAGCTTTGTCTTCTTATAGCTTTGAAGCTTTGCAGCTTTGAGCTTTGAGAATCTGAAGCTTTGGAGCTTTGAGCTTTGGTTGCGCGTAGCTTTGATAGCTTTGCGTAGCTTTGAGCTTTGTAGCTTTGACTAGTGGAGCTTTGTACGCTGCTCAGCTTTGCGAAGCTTTGTAGGCCAGCTTTGCAAGCTTTGAGCTTTGAGCTTTGCAGCTTTGGCCAGCTTTGCAGCTTTGAGCTTTGCCAGCTTTGTAGCTTTGCAGCTTTGCAGCTTTGAGAAAGCTTTGGATTTAGCTTTGAGCTTTGAGCTTTGAGCTTTGAGCTTTGGAGCTTTGTTGAAAGCTTTGAAGCTTTGGAAGCTTTGGGAGCTTTGAGCTTTGCAGCTTTGTCTAGCTTTGTGGAGCTTTGAGCTTTGCAAGCTTTGAGCTTTGAGCTTTGCAGCTTTGTATGGCAGCTTTGTAGCTTTGATGATAGAGCTTTGCTCTCACGTAGCTTTGAGCTTTGAAGCTTTGGCGCTCATTCCGTAGAATTAGCTTTGGAGCTTTGCCTCAGCTTTGCAGCTTTGAGCTTTGAGAGCTTTGTCAATAGCTTTGAGCTTTGATGGAGCTTTGTAAAGCTTTGGAAGTTTACCTATAGCTTTGAGCTTTGCTAGCCGAGCTTTGGGACTTTAGCTTTG'
    pattern = 'AGCTTTGAG'

    print(pattern_count(text, pattern))


if __name__ == '__main__':
    main()
