#!/usr/bin/env python3
# BA1B
# Find the Most Frequent Words in a String


def make_kmers(dna, k):
    """Make all possible kmers of size k from a DNA string."""
    return [dna[i:i+k] for i in range(len(dna) - k + 1)]


def most_frequent_words_in_string(dna, k):
    """Return most frequent kmers in DNA string."""
    from collections import Counter
    kmers = make_kmers(dna, k)
    kmer_counts = Counter(kmers)
    max_freq = kmer_counts.most_common(1)[0][1]
    return [kmer for kmer, count in kmer_counts.items() if count == max_freq]


def main():
    """Find the Most Frequent Words in a String."""
    # dna = 'ACGTTGCATGTCGCATGATGCATGAGAGCT'
    # k = 4

    dna = 'TATCGTCTGGTCGGGTGGCTCGGGTGGCATGCTTAGGAATATTATGGAATATTATGGAATATTATGTCGGGTGGCAGGAATTTCGGAATATTATGAGGAATTTCGAGGAATTTCGAGGAATTTCGTATCGTCTGGTATCGTCTGGAGGAATTTCGTATCGTCTGGAGGAATTTCGATGCTTAGATGCTTAGTCGGGTGGCAGGAATTTCGATGCTTAGTCGGGTGGCATGCTTAGGAATATTATGAGGAATTTCGAGGAATTTCGGAATATTATGGAATATTATGTCGGGTGGCTCGGGTGGCTCGGGTGGCTATCGTCTGGGAATATTATGTATCGTCTGGATGCTTAGTCGGGTGGCGAATATTATGATGCTTAGAGGAATTTCGAGGAATTTCGATGCTTAGATGCTTAGGAATATTATGTCGGGTGGCTATCGTCTGGTATCGTCTGGGAATATTATGTCGGGTGGCAGGAATTTCGTATCGTCTGGTCGGGTGGCTCGGGTGGCTCGGGTGGCATGCTTAGTATCGTCTGGGAATATTATGTATCGTCTGGTCGGGTGGCGAATATTATGTCGGGTGGCTATCGTCTGGTATCGTCTGGTCGGGTGGCAGGAATTTCGGAATATTATGTATCGTCTGGAGGAATTTCGATGCTTAGTCGGGTGGCAGGAATTTCGTATCGTCTGGATGCTTAGAGGAATTTCGTCGGGTGGCATGCTTAGAGGAATTTCGTCGGGTGGCTATCGTCTGGGAATATTATGATGCTTAGGAATATTATGATGCTTAGTCGGGTGGCATGCTTAGTCGGGTGGCATGCTTAGGAATATTATGAGGAATTTCGTATCGTCTGGAGGAATTTCGGAATATTATGTCGGGTGGCAGGAATTTCG'
    k = 11

    freq_kmers = most_frequent_words_in_string(dna, k)
    print(*freq_kmers)


if __name__ == '__main__':
    main()
